service: milsim

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  environment:
    EC2_INSTANCE_ID: ${env:EC2_INSTANCE_ID}

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: milsim.seyacat.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2

functions:
  startInstance:
    handler: index.handler
    events:
      - http:
          path: /start
          method: get
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ec2:DescribeInstances
          - ec2:StartInstances
        Resource: "*"
